// AUTO-GENERATED by tools/sync-commonmark.py — DO NOT EDIT MANUALLY.
// CommonMark spec version: 0.31.2
// Section: Blank lines
// Examples: 1 (skipped: 0)
//
// Источник:    https://spec.commonmark.org/0.31.2/spec.txt
// Регенерация: python tools/sync-commonmark.py 0.31.2

#Использовать asserts
#Использовать "../../src"

Перем _Настройки;

&ОтображаемоеИмя("commonmark_0_31_2_Blank_lines")
&ТестовыйНабор
Процедура ПриСозданииОбъекта() Экспорт
    _Настройки = Новый MarkdownНастройки("commonmark");
КонецПроцедуры

Процедура ПроверитьПример(Знач Номер, Знач Исходник, Знач ОжидаемыйHTML) Экспорт
    Фактический = Markdown.ВHTML(Исходник, _Настройки);
    Утверждения.ПроверитьРавенство(ОжидаемыйHTML, Фактический,
        "CommonMark #" + Номер + " [Blank lines]");
КонецПроцедуры

&Тест
Процедура Пример_0227() Экспорт
    Исходник = "  
        |
        |aaa
        |  
        |
        |# aaa
        |
        |  
        |";
    Ожидаемый = "<p>aaa</p>
        |<h1>aaa</h1>
        |";
    ПроверитьПример(227, Исходник, Ожидаемый);
КонецПроцедуры

