// AUTO-GENERATED by tools/sync-commonmark.py — DO NOT EDIT MANUALLY.
// CommonMark spec version: 0.31.2
// Section: Inlines
// Examples: 1 (skipped: 0)
//
// Источник:    https://spec.commonmark.org/0.31.2/spec.txt
// Регенерация: python tools/sync-commonmark.py 0.31.2

#Использовать asserts
#Использовать "../../src"

Перем _Настройки;

&ОтображаемоеИмя("commonmark_0_31_2_Inlines")
&ТестовыйНабор
Процедура ПриСозданииОбъекта() Экспорт
    _Настройки = Новый MarkdownНастройки("commonmark");
КонецПроцедуры

Процедура ПроверитьПример(Знач Номер, Знач Исходник, Знач ОжидаемыйHTML) Экспорт
    Фактический = Markdown.ВHTML(Исходник, _Настройки);
    Утверждения.ПроверитьРавенство(ОжидаемыйHTML, Фактический,
        "CommonMark #" + Номер + " [Inlines]");
КонецПроцедуры

&Тест
Процедура Пример_0327() Экспорт
    Исходник = "`hi`lo`
        |";
    Ожидаемый = "<p><code>hi</code>lo`</p>
        |";
    ПроверитьПример(327, Исходник, Ожидаемый);
КонецПроцедуры

