// AUTO-GENERATED by tools/sync-commonmark.py — DO NOT EDIT MANUALLY.
// CommonMark spec version: 0.31.2
// Section: Precedence
// Examples: 1 (skipped: 1)
//
// Источник:    https://spec.commonmark.org/0.31.2/spec.txt
// Регенерация: python tools/sync-commonmark.py 0.31.2

#Использовать asserts
#Использовать "../../src"

Перем _Настройки;

&ОтображаемоеИмя("commonmark_0_31_2_Precedence")
&ТестовыйНабор
Процедура ПриСозданииОбъекта() Экспорт
    _Настройки = Новый MarkdownНастройки("commonmark");
КонецПроцедуры

Процедура ПроверитьПример(Знач Номер, Знач Исходник, Знач ОжидаемыйHTML) Экспорт
    Фактический = Markdown.ВHTML(Исходник, _Настройки);
    Утверждения.ПроверитьРавенство(ОжидаемыйHTML, Фактический,
        "CommonMark #" + Номер + " [Precedence]");
КонецПроцедуры

&Тест
&Выключен("Precedence: list interaction")
Процедура Пример_0042() Экспорт
    Исходник = "- `one
        |- two`
        |";
    Ожидаемый = "<ul>
        |<li>`one</li>
        |<li>two`</li>
        |</ul>
        |";
    ПроверитьПример(42, Исходник, Ожидаемый);
КонецПроцедуры

